import React, { useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import ProfileModal from "./ProfileModal";
import ComparisonModal from "./ComparisonModal"; // <--- IMPORT MODAL BARU

const ResultTable = ({ data }) => {
  const [selectedUser, setSelectedUser] = useState(null); // Untuk Modal Profile
  const [compareList, setCompareList] = useState([]); // Untuk List Perbandingan (Checkbox)
  const [isCompareOpen, setIsCompareOpen] = useState(false); // Untuk Modal Perbandingan

  // Helper Format Angka
  const formatNumber = (num) => {
    if (num >= 1000000000) return (num / 1000000000).toFixed(1) + "B";
    if (num >= 1000000) return (num / 1000000).toFixed(1) + "M";
    if (num >= 1000) return (num / 1000).toFixed(1) + "K";
    return num;
  };

  // --- LOGIC CHECKBOX ---
  const handleCheckboxChange = (e, item) => {
    e.stopPropagation(); // Biar baris tidak terklik (modal profile gak muncul)
    if (e.target.checked) {
      if (compareList.length >= 3) {
        alert("Maksimal bandingkan 3 influencer sekaligus!");
        return;
      }
      setCompareList([...compareList, item]);
    } else {
      setCompareList(
        compareList.filter((i) => i.channel_info !== item.channel_info)
      );
    }
  };

  // --- PDF EXPORT ---
  const handleExportPDF = (e) => {
    e.stopPropagation();
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.text("Laporan Rekomendasi Influencer", 14, 22);
    doc.setFontSize(11);
    doc.setTextColor(100);
    const date = new Date().toLocaleDateString("id-ID", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
    doc.text(`Generated by InfluencerMatch DSS | Tanggal: ${date}`, 14, 30);

    const tableColumn = [
      "Rank",
      "Nama Channel",
      "Followers",
      "Eng. Rate",
      "Core",
      "Sec",
      "Score",
    ];
    const tableRows = [];
    data.slice(0, 20).forEach((item, index) => {
      tableRows.push([
        index + 1,
        item.channel_info,
        formatNumber(item.followers),
        (item.eng_rate * 100).toFixed(2) + "%",
        item.calculation.NCF,
        item.calculation.NSF,
        item.calculation.final_score,
      ]);
    });

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 40,
      theme: "grid",
      headStyles: { fillColor: [37, 99, 235] },
      styles: { fontSize: 10, cellPadding: 3 },
    });
    const finalY = doc.lastAutoTable.finalY + 10;
    doc.setFontSize(10);
    doc.text(
      "Catatan: Keputusan akhir tetap berada di tangan pengguna.",
      14,
      finalY
    );
    doc.save(`Laporan_Influencer_${Date.now()}.pdf`);
  };

  if (!data || data.length === 0) {
    return (
      <div className="bg-white p-12 rounded-xl shadow-sm border border-slate-200 text-center animate-fade-in">
        <div className="text-6xl mb-4">📊</div>
        <h3 className="text-xl font-bold text-slate-700">Belum ada data</h3>
        <p className="text-slate-500">
          Silakan atur kriteria di samping dan klik Analisis.
        </p>
      </div>
    );
  }

  return (
    <>
      {/* --- MODALS --- */}
      <ProfileModal
        isOpen={!!selectedUser}
        onClose={() => setSelectedUser(null)}
        data={selectedUser}
      />
      <ComparisonModal
        isOpen={isCompareOpen}
        onClose={() => setIsCompareOpen(false)}
        users={compareList}
      />

      {/* --- FLOATING COMPARE BAR (Muncul jika ada yang dicentang) --- */}
      {compareList.length > 0 && (
        <div className="fixed bottom-6 left-1/2 transform -translate-x-1/2 z-40 bg-slate-900 text-white px-6 py-3 rounded-full shadow-2xl flex items-center gap-4 animate-bounce-in">
          <span className="font-bold text-sm">
            {compareList.length} Dipilih
          </span>
          <button
            onClick={() => setIsCompareOpen(true)}
            className="bg-blue-600 hover:bg-blue-500 text-white px-4 py-1.5 rounded-full text-sm font-bold transition-all disabled:opacity-50"
            disabled={compareList.length < 2}
          >
            {compareList.length < 2 ? "Pilih min 2" : "⚖️ Bandingkan Sekarang"}
          </button>
          <button
            onClick={() => setCompareList([])}
            className="text-slate-400 hover:text-white"
          >
            ✕
          </button>
        </div>
      )}

      <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden animate-fade-in-up">
        {/* Header Tabel */}
        <div className="p-6 border-b border-slate-100 flex flex-col sm:flex-row justify-between items-center gap-4">
          <div>
            <h2 className="text-xl font-bold text-slate-800">
              🏆 Top Recommendations
            </h2>
            <div className="flex gap-2 mt-1">
              <span className="bg-green-100 text-green-700 text-xs font-bold px-3 py-1 rounded-full">
                {data.length} Kandidat
              </span>
              <span className="text-xs text-slate-400">
                Centang kotak untuk membandingkan
              </span>
            </div>
          </div>
          <button
            onClick={handleExportPDF}
            className="flex items-center gap-2 bg-red-50 text-red-600 px-4 py-2 rounded-lg text-sm font-bold hover:bg-red-100 border border-red-100"
          >
            Download PDF
          </button>
        </div>

        {/* Tabel */}
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead className="bg-slate-50">
              <tr>
                <th className="p-4 w-12 text-center text-xs font-bold text-slate-500 uppercase">
                  VS
                </th>
                <th className="p-4 text-xs font-bold text-slate-500 uppercase">
                  Rank
                </th>
                <th className="p-4 text-xs font-bold text-slate-500 uppercase">
                  Profile
                </th>
                <th className="p-4 text-xs font-bold text-slate-500 uppercase text-right">
                  Followers
                </th>
                <th className="p-4 text-xs font-bold text-slate-500 uppercase text-right">
                  Eng. Rate
                </th>
                <th className="p-4 text-xs font-bold text-slate-500 uppercase text-center">
                  Final Score
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {data.map((item, index) => {
                const isSelected = compareList.some(
                  (i) => i.channel_info === item.channel_info
                );
                return (
                  <tr
                    key={index}
                    onClick={() => setSelectedUser(item)}
                    className={`hover:bg-blue-50/50 transition-colors cursor-pointer group ${
                      isSelected ? "bg-blue-50" : ""
                    }`}
                  >
                    {/* CHECKBOX COLUMN */}
                    <td
                      className="p-4 text-center"
                      onClick={(e) => e.stopPropagation()}
                    >
                      <input
                        type="checkbox"
                        checked={isSelected}
                        onChange={(e) => handleCheckboxChange(e, item)}
                        className="w-5 h-5 text-blue-600 rounded border-slate-300 focus:ring-blue-500 cursor-pointer"
                      />
                    </td>

                    <td className="p-4">
                      <div
                        className={`w-8 h-8 flex items-center justify-center rounded-full font-bold text-sm 
                        ${
                          index === 0
                            ? "bg-yellow-100 text-yellow-700"
                            : "bg-slate-200 text-slate-700"
                        }`}
                      >
                        #{index + 1}
                      </div>
                    </td>
                    <td className="p-4">
                      <div className="font-bold text-slate-800 text-base">
                        @{item.channel_info}
                      </div>
                      <div className="text-xs text-slate-500">
                        {item.country || "Global"}
                      </div>
                    </td>
                    <td className="p-4 text-right font-medium text-slate-600">
                      {formatNumber(item.followers)}
                    </td>
                    <td className="p-4 text-right font-medium text-slate-600">
                      {(item.eng_rate * 100).toFixed(2)}%
                    </td>
                    <td className="p-4 text-center">
                      <span className="text-lg font-extrabold text-green-600">
                        {item.calculation.final_score}
                      </span>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
};

export default ResultTable;
