import React, { useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { 
  Trophy, 
  Download, 
  Check, 
  X, 
  ArrowRightLeft, 
  FileText, 
  AlertCircle,
  ExternalLink 
} from "lucide-react";

// Pastikan import modal tetap ada
import ProfileModal from "./ProfileModal";
import ComparisonModal from "./ComparisonModal"; 

const ResultTable = ({ data }) => {
  const [selectedUser, setSelectedUser] = useState(null);
  const [compareList, setCompareList] = useState([]);
  const [isCompareOpen, setIsCompareOpen] = useState(false);

  // Helper Format Angka
  const formatNumber = (num) => {
    if (num >= 1000000000) return (num / 1000000000).toFixed(1) + "B";
    if (num >= 1000000) return (num / 1000000).toFixed(1) + "M";
    if (num >= 1000) return (num / 1000).toFixed(1) + "K";
    return num;
  };

  // --- LOGIC CHECKBOX ---
  const handleCheckboxChange = (e, item) => {
    e.stopPropagation(); 
    if (e.target.checked) {
      if (compareList.length >= 3) {
        alert("Maksimal bandingkan 3 influencer sekaligus!");
        return;
      }
      setCompareList([...compareList, item]);
    } else {
      setCompareList(
        compareList.filter((i) => i.channel_info !== item.channel_info)
      );
    }
  };

  // --- PDF EXPORT (Logic Tetap Sama) ---
  const handleExportPDF = (e) => {
    e.stopPropagation();
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.text("Laporan Rekomendasi Influencer", 14, 22);
    doc.setFontSize(11);
    doc.setTextColor(100);
    const date = new Date().toLocaleDateString("id-ID", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
    doc.text(`Generated by InfluencerMatch DSS | Tanggal: ${date}`, 14, 30);

    const tableColumn = ["Rank", "Nama Channel", "Followers", "Eng. Rate", "Core", "Sec", "Score"];
    const tableRows = [];
    data.slice(0, 20).forEach((item, index) => {
      tableRows.push([
        index + 1,
        item.channel_info,
        formatNumber(item.followers),
        (item.eng_rate * 100).toFixed(2) + "%",
        item.calculation.NCF,
        item.calculation.NSF,
        item.calculation.final_score,
      ]);
    });

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 40,
      theme: "grid",
      headStyles: { fillColor: [79, 70, 229] }, // Brand Color Indigo
      styles: { fontSize: 10, cellPadding: 3 },
    });
    const finalY = doc.lastAutoTable.finalY + 10;
    doc.setFontSize(10);
    doc.text("Catatan: Keputusan akhir tetap berada di tangan pengguna.", 14, finalY);
    doc.save(`Laporan_Influencer_${Date.now()}.pdf`);
  };

  // --- EMPTY STATE ---
  if (!data || data.length === 0) {
    return (
      <div className="bg-white dark:bg-darkCard p-12 rounded-3xl shadow-sm border border-slate-200 dark:border-slate-800 text-center animate-fade-in border-dashed border-2">
        <div className="w-20 h-20 bg-slate-50 dark:bg-slate-900 rounded-full flex items-center justify-center mx-auto mb-4 text-slate-400">
          <AlertCircle size={40} />
        </div>
        <h3 className="text-xl font-bold text-slate-800 dark:text-white">Belum ada data</h3>
        <p className="text-slate-500 dark:text-slate-400 mt-2">
          Silakan atur kriteria di sidebar dan klik tombol Analisis.
        </p>
      </div>
    );
  }

  return (
    <>
      {/* --- MODALS --- */}
      <ProfileModal
        isOpen={!!selectedUser}
        onClose={() => setSelectedUser(null)}
        data={selectedUser}
      />
      <ComparisonModal
        isOpen={isCompareOpen}
        onClose={() => setIsCompareOpen(false)}
        users={compareList}
      />

      {/* --- FLOATING COMPARE BAR --- */}
      {compareList.length > 0 && (
        <div className="fixed bottom-10 left-1/2 transform -translate-x-1/2 z-50 animate-in slide-in-from-bottom-5 duration-300">
          <div className="bg-slate-900/90 dark:bg-brand-900/90 backdrop-blur-md text-white px-6 py-3 rounded-full shadow-2xl flex items-center gap-5 border border-slate-700">
            <div className="flex items-center gap-2">
              <span className="bg-brand-500 w-6 h-6 rounded-full flex items-center justify-center text-[10px] font-bold">
                {compareList.length}
              </span>
              <span className="font-semibold text-sm">Kandidat Dipilih</span>
            </div>
            
            <div className="h-4 w-[1px] bg-slate-600"></div>

            <button
              onClick={() => setIsCompareOpen(true)}
              disabled={compareList.length < 2}
              className="flex items-center gap-2 bg-white text-slate-900 hover:bg-slate-100 px-5 py-2 rounded-full text-xs font-bold transition-all disabled:opacity-50 disabled:cursor-not-allowed uppercase tracking-wider"
            >
              <ArrowRightLeft size={14} /> Bandingkan
            </button>
            <button
              onClick={() => setCompareList([])}
              className="p-1 hover:bg-white/10 rounded-full transition-colors"
            >
              <X size={18} className="text-slate-400 hover:text-white" />
            </button>
          </div>
        </div>
      )}

      {/* --- TABLE CONTAINER --- */}
      <div className="bg-white dark:bg-darkCard rounded-4xl shadow-premium border border-slate-200 dark:border-slate-800 overflow-hidden transition-colors">
        
        {/* Header Tabel */}
        <div className="p-8 border-b border-slate-100 dark:border-slate-800 flex flex-col sm:flex-row justify-between items-center gap-4">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <Trophy className="text-yellow-500" size={20} />
              <h2 className="text-xl font-black text-slate-800 dark:text-white tracking-tight">
                Top Recommendations
              </h2>
            </div>
            <div className="flex gap-3 text-xs font-medium">
              <span className="text-brand-600 dark:text-brand-400 bg-brand-50 dark:bg-brand-900/30 px-3 py-1 rounded-full border border-brand-100 dark:border-brand-800">
                {data.length} Kandidat Ditemukan
              </span>
              <span className="text-slate-400 flex items-center gap-1">
                <Check size={12} /> Pilih untuk bandingkan
              </span>
            </div>
          </div>

          <button
            onClick={handleExportPDF}
            className="group flex items-center gap-2 bg-slate-50 dark:bg-slate-800 text-slate-600 dark:text-slate-300 px-5 py-2.5 rounded-full text-sm font-bold hover:bg-red-50 hover:text-red-600 dark:hover:bg-red-900/20 dark:hover:text-red-400 border border-slate-200 dark:border-slate-700 transition-all shadow-sm hover:shadow-md"
          >
            <Download size={16} className="group-hover:animate-bounce" />
            <span className="hidden sm:inline">Download PDF</span>
          </button>
        </div>

        {/* Tabel */}
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead className="bg-slate-50 dark:bg-darkBg/50">
              <tr className="text-slate-400 text-[10px] font-black uppercase tracking-[0.2em]">
                <th className="p-6 text-center w-16">VS</th>
                <th className="p-6 w-20">Rank</th>
                <th className="p-6">Influencer Profile</th>
                <th className="p-6 text-right">Followers</th>
                <th className="p-6 text-right">Engagement</th>
                <th className="p-6 text-center">Final Score</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
              {data.map((item, index) => {
                const isSelected = compareList.some((i) => i.channel_info === item.channel_info);
                
                // Style untuk Ranking 1, 2, 3
                let rankStyle = "bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-400";
                if (index === 0) rankStyle = "bg-yellow-100 text-yellow-700 ring-4 ring-yellow-50 dark:bg-yellow-900/30 dark:text-yellow-400 dark:ring-yellow-900/10";
                if (index === 1) rankStyle = "bg-gray-100 text-slate-700 ring-4 ring-gray-50 dark:bg-slate-700 dark:text-slate-200 dark:ring-slate-700/50";
                if (index === 2) rankStyle = "bg-orange-100 text-orange-800 ring-4 ring-orange-50 dark:bg-orange-900/30 dark:text-orange-400 dark:ring-orange-900/10";

                return (
                  <tr
                    key={index}
                    onClick={() => setSelectedUser(item)}
                    className={`group transition-all cursor-pointer ${
                      isSelected 
                        ? "bg-brand-50/50 dark:bg-brand-900/10" 
                        : "hover:bg-slate-50 dark:hover:bg-slate-800/40"
                    }`}
                  >
                    {/* CHECKBOX */}
                    <td className="p-6 text-center" onClick={(e) => e.stopPropagation()}>
                      <div className="relative flex items-center justify-center">
                        <input
                          type="checkbox"
                          checked={isSelected}
                          onChange={(e) => handleCheckboxChange(e, item)}
                          className="peer appearance-none w-5 h-5 border-2 border-slate-300 dark:border-slate-600 rounded-md checked:bg-brand-500 checked:border-brand-500 transition-colors cursor-pointer"
                        />
                        <Check size={12} className="absolute text-white opacity-0 peer-checked:opacity-100 pointer-events-none" />
                      </div>
                    </td>

                    {/* RANK */}
                    <td className="p-6">
                      <div className={`w-10 h-10 flex items-center justify-center rounded-xl font-black text-sm transition-all ${rankStyle}`}>
                        #{index + 1}
                      </div>
                    </td>

                    {/* PROFILE */}
                    <td className="p-6">
                      <div className="flex items-center gap-4">
                         {/* Avatar Placeholder */}
                        <div className="w-10 h-10 rounded-full bg-gradient-to-tr from-brand-300 to-indigo-500 flex items-center justify-center text-white font-bold uppercase shadow-md">
                          {item.channel_info.substring(0, 2)}
                        </div>
                        <div>
                          <div className="flex items-center gap-2">
                            <span className="font-bold text-slate-800 dark:text-white text-base">
                              @{item.channel_info}
                            </span>
                            <ExternalLink size={12} className="text-slate-300 hover:text-brand-500" />
                          </div>
                          <div className="text-xs font-medium text-slate-400 mt-0.5 flex items-center gap-1">
                            <span className={`w-2 h-2 rounded-full ${item.country ? 'bg-green-400' : 'bg-slate-300'}`}></span>
                            {item.country || "Global Region"}
                          </div>
                        </div>
                      </div>
                    </td>

                    {/* DATA COLUMNS */}
                    <td className="p-6 text-right font-bold text-slate-600 dark:text-slate-300">
                      {formatNumber(item.followers)}
                    </td>
                    <td className="p-6 text-right">
                      <span className={`inline-block px-2 py-1 rounded text-xs font-bold ${
                        item.eng_rate > 0.05 
                          ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400' 
                          : 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-400'
                      }`}>
                        {(item.eng_rate * 100).toFixed(2)}%
                      </span>
                    </td>

                    {/* FINAL SCORE */}
                    <td className="p-6 text-center">
                      <div className="relative inline-flex items-center justify-center">
                         {/* Circular Progress (Visual only) */}
                        <svg className="w-12 h-12 transform -rotate-90">
                          <circle cx="24" cy="24" r="20" stroke="currentColor" strokeWidth="4" fill="transparent" className="text-slate-200 dark:text-slate-700" />
                          <circle cx="24" cy="24" r="20" stroke="currentColor" strokeWidth="4" fill="transparent" 
                            strokeDasharray={2 * Math.PI * 20}
                            strokeDashoffset={2 * Math.PI * 20 * (1 - item.calculation.final_score / 100)} // Asumsi score max 100, sesuaikan jika skala 1-10
                            className="text-brand-500" 
                          />
                        </svg>
                        <span className="absolute text-sm font-black text-brand-600 dark:text-white">
                          {parseFloat(item.calculation.final_score).toFixed(1)}
                        </span>
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
};

export default ResultTable;